spring:
  app:
    jwtSecret: s3cr37
    jwtExpirationMs: 36000000
  datasource:
    url: jdbc:postgresql://YOUR CONNECTION STRING
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  address: YOUR IP
  port: 8081