spring:
  app:
    jwtSecret: s3cr37
    jwtExpirationMs: 36000000
  datasource:
    url: URL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  address: 192.168.0.105
  port: 8081
